/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
import UIBaseView from './../UIBaseView';
import SideView from "../model/SideView";
UIBaseView.init();
SideView.init();
var REG: Function = Laya.ClassUtils.regClass;
export module ui.item {
    export class MoreGameItem1UI extends Laya.View {
		public imgIcon:Laya.Image;
		public lblName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("item/MoreGameItem1");
        }
    }
    REG("ui.item.MoreGameItem1UI",MoreGameItem1UI);
    export class SideBotItemUI extends Laya.View {
		public ani1:Laya.FrameAnimation;
		public imgIcon:Laya.Image;
		public imgNew:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("item/SideBotItem");
        }
    }
    REG("ui.item.SideBotItemUI",SideBotItemUI);
    export class SideGridItemUI extends Laya.View {
		public ani1:Laya.FrameAnimation;
		public imgIcon:Laya.Image;
		public lblName:Laya.Label;
		public imgNew:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("item/SideGridItem");
        }
    }
    REG("ui.item.SideGridItemUI",SideGridItemUI);
    export class SideListItemUI extends Laya.View {
		public imgIcon:Laya.Image;
		public imgRed:Laya.Image;
		public lblName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("item/SideListItem");
        }
    }
    REG("ui.item.SideListItemUI",SideListItemUI);
    export class SideNewItemUI extends Laya.View {
		public ani1:Laya.FrameAnimation;
		public imgIcon:Laya.Image;
		public lblName:Laya.Label;
		public imgNew:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("item/SideNewItem");
        }
    }
    REG("ui.item.SideNewItemUI",SideNewItemUI);
}
export module ui.side {
    export class SideBotListUI extends Laya.SideView {
		public ltCont:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("side/SideBotList");
        }
    }
    REG("ui.side.SideBotListUI",SideBotListUI);
    export class SideGridUI extends Laya.SideView {
		public ltCont:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("side/SideGrid");
        }
    }
    REG("ui.side.SideGridUI",SideGridUI);
    export class SideIconRTUI extends Laya.SideView {
		public imgIcon:Laya.Image;
		public imgBg:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("side/SideIconRT");
        }
    }
    REG("ui.side.SideIconRTUI",SideIconRTUI);
}
export module ui.view {
    export class DebugViewUI extends Laya.UIBaseView {
		public list:Laya.List;
		public btnBox:Laya.Box;
		public btnClear:Laya.Button;
		public btnClose:Laya.Button;
		public imput_Num:Laya.TextInput;
		public btn_makeSure:Laya.Button;
		public btn_server:Laya.Button;
		public input_money:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/DebugView");
        }
    }
    REG("ui.view.DebugViewUI",DebugViewUI);
    export class FailViewUI extends Laya.UIBaseView {
		public lblProb:Laya.Label;
		public sideGrid:any;
		public imgRestart:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/FailView");
        }
    }
    REG("ui.view.FailViewUI",FailViewUI);
    export class HomeViewUI extends Laya.UIBaseView {
		public vwMain:Laya.View;
		public imgRelay:Laya.Image;
		public imgGoldBg:Laya.Image;
		public lblGold:Laya.Label;
		public imgGold:Laya.Image;
		public imgMore:Laya.Image;
		public imgSkin:Laya.Image;
		public imgStart:Laya.Image;
		public sideList:any;
		public sideIcon0:any;
		public vwGame:Laya.View;
		public imgPause:Laya.Image;
		public sideIcon1:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/HomeView");
        }
    }
    REG("ui.view.HomeViewUI",HomeViewUI);
    export class LoadingUI extends Laya.UIBaseView {
		public bar:Laya.ProgressBar;
		public txt:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/Loading");
        }
    }
    REG("ui.view.LoadingUI",LoadingUI);
    export class RankingViewUI extends Laya.UIBaseView {
		public wxOpenDataSp:laya.ui.WXOpenDataViewer;
		public btnExit:Laya.Button;
		public btnRanking:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/RankingView");
        }
    }
    REG("ui.view.RankingViewUI",RankingViewUI);
    export class ResultViewUI extends Laya.UIBaseView {
		public lblGold:Laya.Label;
		public imgGold:Laya.Image;
		public lblLevel:Laya.Label;
		public lblAddGold:Laya.Label;
		public flyGold:any;
		public sideGrid:any;
		public imgClose:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/ResultView");
        }
    }
    REG("ui.view.ResultViewUI",ResultViewUI);
}