/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
import UIBaseView from './../UIBaseView';
import SideView from "../side/view/SideView";
UIBaseView.init();
SideView.init();
var REG: Function = Laya.ClassUtils.regClass;
export module ui.view {
    export class DebugViewUI extends Laya.UIBaseView {
		public list:Laya.List;
		public btnBox:Laya.Box;
		public btnClear:Laya.Button;
		public btnClose:Laya.Button;
		public imput_Num:Laya.TextInput;
		public btn_makeSure:Laya.Button;
		public btn_server:Laya.Button;
		public input_money:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/DebugView");
        }
    }
    REG("ui.view.DebugViewUI",DebugViewUI);
    export class FailViewUI extends Laya.UIBaseView {
		public lblProb:Laya.Label;
		public sideGrid:any;
		public imgRestart:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/FailView");
        }
    }
    REG("ui.view.FailViewUI",FailViewUI);
    export class HomeSellViewUI extends Laya.UIBaseView {
		public addIconAni:Laya.FrameAnimation;
		public btnMoreGame:Laya.Image;
		public nativeBg:Laya.Image;
		public nativeIcon:Laya.Image;
		public sell:any;
		public addDesktop:Laya.Box;
		public addDesktopIcon:Laya.Image;
		public handImg:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/HomeSellView");
        }
    }
    REG("ui.view.HomeSellViewUI",HomeSellViewUI);
    export class HomeViewUI extends Laya.UIBaseView {
		public vwMain:Laya.View;
		public btnStart:Laya.Image;
		public sideLeft:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/HomeView");
        }
    }
    REG("ui.view.HomeViewUI",HomeViewUI);
    export class LoadingViewUI extends Laya.UIBaseView {
		public bar:Laya.ProgressBar;
		public txt:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/LoadingView");
        }
    }
    REG("ui.view.LoadingViewUI",LoadingViewUI);
    export class RankingViewUI extends Laya.UIBaseView {
		public wxOpenDataSp:laya.ui.WXOpenDataViewer;
		public btnExit:Laya.Button;
		public btnRanking:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/RankingView");
        }
    }
    REG("ui.view.RankingViewUI",RankingViewUI);
    export class ResultViewUI extends Laya.UIBaseView {
		public lblGold:Laya.Label;
		public imgGold:Laya.Image;
		public lblLevel:Laya.Label;
		public lblAddGold:Laya.Label;
		public flyGold:any;
		public sideGrid:any;
		public imgClose:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/ResultView");
        }
    }
    REG("ui.view.ResultViewUI",ResultViewUI);
}
export module ui.view.item {
    export class BigBoxItem0UI extends Laya.View {
		public imgIcon:Laya.Image;
		public labelname:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/BigBoxItem0");
        }
    }
    REG("ui.view.item.BigBoxItem0UI",BigBoxItem0UI);
    export class BigBoxItem1UI extends Laya.View {
		public imgIcon:Laya.Image;
		public lblName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/BigBoxItem1");
        }
    }
    REG("ui.view.item.BigBoxItem1UI",BigBoxItem1UI);
    export class MoreGameItem1UI extends Laya.View {
		public imgIcon:Laya.Image;
		public lblName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/MoreGameItem1");
        }
    }
    REG("ui.view.item.MoreGameItem1UI",MoreGameItem1UI);
    export class OverGameItemUI extends Laya.View {
		public imgIcon:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/OverGameItem");
        }
    }
    REG("ui.view.item.OverGameItemUI",OverGameItemUI);
    export class SideBotItemUI extends Laya.View {
		public ani1:Laya.FrameAnimation;
		public imgIcon:Laya.Image;
		public imgNew:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/SideBotItem");
        }
    }
    REG("ui.view.item.SideBotItemUI",SideBotItemUI);
    export class SideBoxItemUI extends Laya.View {
		public icon:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/SideBoxItem");
        }
    }
    REG("ui.view.item.SideBoxItemUI",SideBoxItemUI);
    export class SideBoxItem0UI extends Laya.View {
		public imgIcon:Laya.Image;
		public labelname:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/SideBoxItem0");
        }
    }
    REG("ui.view.item.SideBoxItem0UI",SideBoxItem0UI);
    export class SideBoxItem1UI extends Laya.View {
		public imgIcon:Laya.Image;
		public lblName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/SideBoxItem1");
        }
    }
    REG("ui.view.item.SideBoxItem1UI",SideBoxItem1UI);
    export class SideGridItemUI extends Laya.View {
		public ani1:Laya.FrameAnimation;
		public imgIcon:Laya.Image;
		public lblName:Laya.Label;
		public imgNew:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/SideGridItem");
        }
    }
    REG("ui.view.item.SideGridItemUI",SideGridItemUI);
    export class SideListItemUI extends Laya.View {
		public imgIcon:Laya.Image;
		public imgRed:Laya.Image;
		public lblName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/SideListItem");
        }
    }
    REG("ui.view.item.SideListItemUI",SideListItemUI);
    export class SideListItem4UI extends Laya.View {
		public imgIcon:Laya.Image;
		public imgRed:Laya.Image;
		public lblName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/SideListItem4");
        }
    }
    REG("ui.view.item.SideListItem4UI",SideListItem4UI);
    export class SideNewItemUI extends Laya.View {
		public ani1:Laya.FrameAnimation;
		public imgIcon:Laya.Image;
		public lblName:Laya.Label;
		public imgNew:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/SideNewItem");
        }
    }
    REG("ui.view.item.SideNewItemUI",SideNewItemUI);
    export class WXModelItemUI extends Laya.View {
		public imgIcon:Laya.Image;
		public lblName:Laya.Label;
		public imgStar:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/item/WXModelItem");
        }
    }
    REG("ui.view.item.WXModelItemUI",WXModelItemUI);
}
export module ui.view.side {
    export class BigBoxViewUI extends Laya.SideView {
		public boxTop:Laya.Box;
		public imgBack:Laya.Image;
		public list0:Laya.List;
		public list1:Laya.List;
		public imgKeep:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/BigBoxView");
        }
    }
    REG("ui.view.side.BigBoxViewUI",BigBoxViewUI);
    export class GoldenEggViewUI extends Laya.UIBaseView {
		public ani1:Laya.FrameAnimation;
		public imgEgg:Laya.Image;
		public spMask:Laya.Sprite;
		public imgBtn:Laya.Image;
		public imgHand:Laya.Image;
		public lblRem:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/GoldenEggView");
        }
    }
    REG("ui.view.side.GoldenEggViewUI",GoldenEggViewUI);
    export class MorePeopleViewUI extends Laya.SideView {
		public list:Laya.List;
		public btn_close:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/MorePeopleView");
        }
    }
    REG("ui.view.side.MorePeopleViewUI",MorePeopleViewUI);
    export class SideBotListUI extends Laya.SideView {
		public ltCont:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/SideBotList");
        }
    }
    REG("ui.view.side.SideBotListUI",SideBotListUI);
    export class SideBoxViewUI extends Laya.SideView {
		public boxTop:Laya.Box;
		public imgBack:Laya.Image;
		public list0:Laya.List;
		public list1:Laya.List;
		public imgKeep:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/SideBoxView");
        }
    }
    REG("ui.view.side.SideBoxViewUI",SideBoxViewUI);
    export class SideDoubleListUI extends Laya.SideView {
		public leftList:Laya.List;
		public rightList:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/SideDoubleList");
        }
    }
    REG("ui.view.side.SideDoubleListUI",SideDoubleListUI);
    export class SideGridUI extends Laya.SideView {
		public ltCont:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/SideGrid");
        }
    }
    REG("ui.view.side.SideGridUI",SideGridUI);
    export class SideIconRTUI extends Laya.SideView {
		public imgIcon:Laya.Image;
		public imgBg:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/SideIconRT");
        }
    }
    REG("ui.view.side.SideIconRTUI",SideIconRTUI);
    export class SideLeftListUI extends Laya.SideView {
		public imgBg:Laya.Image;
		public boxMain:Laya.Box;
		public imgSide:Laya.Image;
		public list:Laya.List;
		public imgSlide:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/SideLeftList");
        }
    }
    REG("ui.view.side.SideLeftListUI",SideLeftListUI);
    export class SideMoreGameViewUI extends Laya.SideView {
		public boxTop:Laya.Box;
		public imgBack:Laya.Image;
		public list0:Laya.List;
		public list1:Laya.List;
		public imgKeep:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/SideMoreGameView");
        }
    }
    REG("ui.view.side.SideMoreGameViewUI",SideMoreGameViewUI);
    export class SideOverListUI extends Laya.SideView {
		public list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/SideOverList");
        }
    }
    REG("ui.view.side.SideOverListUI",SideOverListUI);
    export class WXModelViewUI extends Laya.SideView {
		public spGray:Laya.Sprite;
		public boxTop:Laya.Box;
		public boxBack:Laya.Box;
		public ltCont:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/side/WXModelView");
        }
    }
    REG("ui.view.side.WXModelViewUI",WXModelViewUI);
}